image: "rust:latest"
cache:
  paths:
    - cargo/

before_script:
    - cargo install mdbook

pages:
    script:
        - mdbook build
        - mv book public
    artifacts:
        paths:
            - public/
    only:
        - master
